# 张量的结构操作

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
tf.constant([1,2,3],dtype= tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
tf.range(1,10,delta =2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [4]:
t = tf.reshape(tf.range(1,13,1),[4,3])
t

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [9]:
t[1:3,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>

In [10]:
t = tf.Variable(initial_value=t)
t

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [11]:
t[1].assign(tf.constant([0,0,0]))
t

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 0,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [12]:
t[...,1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  0,  8, 11])>

In [13]:
t = tf.reshape(tf.range(1,28,1),[3,3,3])
t

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [17]:
tf.gather(t,[0,1],axis = 2)

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])>

In [18]:
tf.gather_nd(t,indices=[(0,0),(1,1)])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [13, 14, 15]])>

In [19]:
tf.where(t>12,0,1)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])>

In [20]:
tf.where(t>12,t,0)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [21]:
tf.scatter_nd(tf.where(t<4),tf.gather_nd(t,tf.where(t<4)),t.shape)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])>

In [22]:
t = tf.reshape(t,[1,3,3,3])
t.shape

TensorShape([1, 3, 3, 3])

In [23]:
tf.squeeze(t)

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [24]:
tf.expand_dims(t,axis = 1)

<tf.Tensor: shape=(1, 1, 3, 3, 3), dtype=int32, numpy=
array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]]])>

In [27]:
tf.transpose(t,[2,1,3,0])

<tf.Tensor: shape=(3, 3, 3, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3]],

        [[10],
         [11],
         [12]],

        [[19],
         [20],
         [21]]],


       [[[ 4],
         [ 5],
         [ 6]],

        [[13],
         [14],
         [15]],

        [[22],
         [23],
         [24]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[16],
         [17],
         [18]],

        [[25],
         [26],
         [27]]]])>

In [28]:
a = tf.constant([1,2])
b = tf.constant([4,5])

In [30]:
tf.concat([a,b],axis = 0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 4, 5])>

In [36]:
tf.stack([a,b],axis = 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [34]:
tf.split(t,3,axis =1)

[<tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
 array([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])>,
 <tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
 array([[[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]])>,
 <tf.Tensor: shape=(1, 1, 3, 3), dtype=int32, numpy=
 array([[[[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]])>]

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
help(tf.math.mod)

Help on function floor_mod in module tensorflow.python.ops.gen_math_ops:

floor_mod(x, y, name=None)
    Returns element-wise remainder of division. When `x < 0` xor `y < 0` is
    
    true, this follows Python semantics in that the result here is consistent
    with a flooring divide. E.g. `floor(x / y) * y + mod(x, y) = x`.
    
    *NOTE*: `math.floormod` supports broadcasting. More about broadcasting
    [here](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
    
    Args:
      x: A `Tensor`. Must be one of the following types: `int32`, `int64`, `uint64`, `bfloat16`, `half`, `float32`, `float64`.
      y: A `Tensor`. Must have the same type as `x`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `x`.

