In [1]:
import numpy as np 
import tensorflow as tf

# 常量张量

In [3]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
tf.constant(2,dtype = tf.int64)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [5]:
tf.constant(3.14,dtype = tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=3.14>

In [6]:
tf.constant('hellow,Word')

<tf.Tensor: shape=(), dtype=string, numpy=b'hellow,Word'>

In [7]:
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## 零维标量

In [9]:
scaler = tf.constant(True)
print(tf.rank(scaler))
print(np.ndim(scaler.numpy()))

tf.Tensor(0, shape=(), dtype=int32)
0


## 一维向量

In [12]:
vector = tf.constant([1,2,3,4,5],dtype = tf.double)
print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
1


## 二维矩阵

In [16]:
matrix = tf.constant([[1,2,3],[4,5,6]])
print(tf.rank(matrix))
print(matrix.numpy().ndim)

tf.Tensor(2, shape=(), dtype=int32)
2


In [17]:
tf.constant(np.arange(1,10,1).reshape([3,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

## 多维张量

In [18]:
tf.constant(np.arange(1,17,1).reshape([2,2,2,2]))

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])>

## 更改数据类型

In [19]:
h = tf.constant([1,2,3])
tf.cast(h,tf.double)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

## 查看数据和维度

In [22]:
h = tf.constant(np.random.randn(2,2,2))
print(h.numpy())
print(h.shape)

[[[-0.00600304 -0.45652765]
  [ 0.28591763 -1.85033705]]

 [[-0.61041672 -0.09687707]
  [-0.73555507 -0.0976145 ]]]
(2, 2, 2)


# 变化张量

In [25]:
via = tf.Variable([1,2],name='v')
print(via,id(via))
via.assign_add([1,1])
print(via,id(via))

<tf.Variable 'v:0' shape=(2,) dtype=int32, numpy=array([1, 2])> 2105558160528
<tf.Variable 'v:0' shape=(2,) dtype=int32, numpy=array([2, 3])> 2105558160528


# 动态计算图

In [28]:
# 定义计算图
x = tf.constant('Hello')
y = tf.constant('World')
z = tf.strings.join([x,y],separator = ',')
tf.print(z)

Hello,World


In [29]:
def string_join(x,y):
    z = tf.strings.join([x,y],separator=' ')
    tf.print(z)
    return z

In [30]:
string_join(x,y)

Hello World


<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

# Autographe

In [31]:
@tf.function
def strjoin(x,y):
    z = tf.strings.join([x,y],separator=' ')
    tf.print(z)
    return z

strjoin(x,y)

Hello World


<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World'>

In [34]:
import datetime
import os 

stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = os.path.join('data','autograph',stamp)

writer = tf.summary.create_file_writer(logdir)

tf.summary.trace_on(graph=True,profiler=True)

result = strjoin('Hello','World')

with writer.as_default():
    tf.summary.trace_export(name='autograph',step=0,profiler_outdir=logdir)


Instructions for updating:
use `tf.profiler.experimental.start` instead.
Hello World
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
