# 张量的结构操作

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.constant([1,2,3],dtype= tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
tf.range(1,10,delta =2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [5]:
tf.linspace(0,10,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])>

In [6]:
tf.zeros([0,3,3])

<tf.Tensor: shape=(0, 3, 3), dtype=float32, numpy=array([], shape=(0, 3, 3), dtype=float32)>

In [7]:
# 均匀分布
tf.random.uniform([5],minval = 0,maxval = 10)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([2.896415 , 1.1041951, 9.253302 , 4.310708 , 9.066988 ],
      dtype=float32)>

In [8]:
tf.eye(3,3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [9]:
tf.linalg.diag([3,4,2])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 2]])>

In [10]:
tf.random.set_seed(3)
t = tf.random.uniform([5,5],minval=0,maxval=10,dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [11]:
scores = tf.random.uniform((4,10,7),minval=0,maxval=100,dtype=tf.int32)
tf.print(scores)

[[[27 83 99 ... 70 67 79]
  [6 97 31 ... 3 40 48]
  [71 63 31 ... 44 30 86]
  ...
  [10 94 95 ... 89 1 13]
  [61 6 81 ... 24 46 10]
  [61 20 89 ... 33 95 78]]

 [[26 1 5 ... 2 62 29]
  [40 0 68 ... 37 15 28]
  [70 60 82 ... 72 64 1]
  ...
  [49 60 74 ... 18 87 35]
  [2 38 41 ... 66 8 74]
  [37 12 60 ... 57 29 51]]

 [[33 79 23 ... 5 24 45]
  [66 50 83 ... 32 30 58]
  [47 91 21 ... 59 81 1]
  ...
  [98 93 66 ... 55 67 69]
  [71 93 26 ... 77 11 63]
  [90 75 74 ... 7 68 14]]

 [[72 1 53 ... 97 57 28]
  [24 5 45 ... 41 86 23]
  [99 68 54 ... 97 65 85]
  ...
  [94 4 69 ... 88 17 93]
  [28 48 9 ... 73 32 39]
  [18 2 40 ... 51 37 24]]]


In [12]:
tf.gather(scores,[0,5,9],axis = 1)

<tf.Tensor: shape=(4, 3, 7), dtype=int32, numpy=
array([[[27, 83, 99,  9, 70, 67, 79],
        [96, 78, 75, 17,  2,  3, 49],
        [61, 20, 89,  9, 33, 95, 78]],

       [[26,  1,  5, 17,  2, 62, 29],
        [16, 51, 72, 94, 11, 80, 78],
        [37, 12, 60, 45, 57, 29, 51]],

       [[33, 79, 23, 82,  5, 24, 45],
        [46, 73, 64, 71, 27, 39, 13],
        [90, 75, 74, 12,  7, 68, 14]],

       [[72,  1, 53, 87, 97, 57, 28],
        [84, 99, 85, 71, 79, 57, 62],
        [18,  2, 40, 74, 51, 37, 24]]])>

In [13]:
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
tf.where(c<0,tf.fill(c.shape,np.nan),c)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [14]:
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  1., -1.],
       [ 2.,  2., -2.],
       [ 3., -3.,  3.]], dtype=float32)>